services:
  - type: web
    name: executive-assistant-bot
    env: node
    buildCommand: cd app && npm install && npm run build
    startCommand: cd app && npm start
    envVars:
      - key: PORT
        value: 8443
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        sync: false
    healthCheckPath: /api/telegram/webhook
    autoDeploy: true 