services:
  - type: web
    name: athena-langchain-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-3.5-turbo
      - key: LLM_TEMPERATURE
        value: "0.7"
    healthCheckPath: /health 